Controller
AlexSyssa/testguru pull request #8
Opened 2023-09-11 17:40 UTC by AlexSyssa

2023-09-12 07:09 UTC, BubuntuClu requested changes

2023-09-12 07:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render json: {questions: Question.where(test_id: params[:id] )}
`Question.where(test_id: params[:id]` - этот код дублируется. значит надо вынести в метод.

2023-09-12 07:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def show_question
этот метод не нужен. он покрывается методом `show`

2023-09-12 07:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render json: {questions: Question.where(test_id: params[:id] )}
ты ищешь конкретный вопрос. это метод `find`

2023-09-12 07:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params)
Параметры с фронта могут быть не валидные, это надо учитывать
```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2023-09-12 07:09 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:test_id, :body)
`test_id` тут не нужно передавать. ты его через ассоциацию будешь выставлять

2023-09-12 07:09 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    test = Test.create(test_params)
тоже самое, надо првоерить что тест сохранился

2023-09-12 07:09 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form action="/questions" method="post">
тут надо добавить параметр теста, чтобы роутинг сработал правильно

2023-09-12 07:09 UTC, BubuntuClu commented on config/routes.rb
> + resources :tests
это надо убрать. это дубль ресурса на 9ой строке

2023-09-12 07:09 UTC, BubuntuClu commented on config/routes.rb
> + resources :questions
это надо убрать. у тебя вопросы это вложенный ресурс в тесты

2023-09-12 07:09 UTC, BubuntuClu commented on config/routes.rb
> + get '/show_question/:id', to: 'questions#show_question'
это ненужный метод, удали его

2023-09-12 07:09 UTC, BubuntuClu commented on config/routes.rb
> + resources :questions do
это тоже надо удалить. у тебя уже есть описанный ресурс вопросов в тестах

2023-09-16 16:40 UTC, BubuntuClu requested changes

2023-09-16 16:40 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.new(test_id: params[:test_id], body: params.permit(:body))
создавай вопрос через ассоциацию от теста

2023-09-16 16:40 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render json: {questions: Question.where(test_id: params[:test_id])}
найди тест через колбэк и через ассоциацию вопросы, так кода меньше будет в методе

2023-09-16 16:40 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    render json: {questions: Question.find(params[:id])}
код по пиоску вопроса дублируется в методах. надо вынести в метод и через колбэк их искать

2023-09-16 16:40 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    test = Test.create(test_params)
если ты делаешь `create`, то он сохраняется в базу. и `save` вызовет второй запрос.
надо `create` заменить на `new`

2023-09-16 16:40 UTC, BubuntuClu commented on app/models/user.rb
> +#validates :email, presence: true
надо вернуть. почему отключила?

2023-09-16 16:40 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<%= form_with url: test_questions_path, method: :post do |form| %>
а что со строкой? которую разбирали с тобой

`url` не самый лучший способ, дальше будет показан метод лучше, который строится на объектах.

2023-09-17 02:11 UTC, AlexSyssa commented on app/views/questions/new.html.erb
> +<%= form_with url: test_questions_path, method: :post do |form| %>
оставила этот вариант, потому  что он короче
изначально делала через form_with model, но там выводился url с /new

2023-09-17 10:39 UTC, merged